### PR TITLE
fix: check nv plugin only for known gpu sku

### LINKED ISSUE #1256: Attempt to use preferredNode in RAGEngine custom resource does not work
**Describe the bug**
I'd like to deploy a RAGEngine resource on a CPU-based node in my AKS cluster but the RAGEngine component will not schedule on preferred node even though custom resource configuration seems to be correct. 

**Steps To Reproduce**
1. Run the [terraform script](https://github.com/kaito-project/kaito/tree/main/terraform) to deploy KAITO
2. Add a new node pool to the KAITO enabled cluster and note the node name

```
az aks nodepool add \
--resource-group $(terraform output -raw rg_name) \
--cluster-name $(terraform output -raw aks_name) \
--name ragpool \
-s standard_d8as_v4 \
-c 1 \
--labels apps=phi-4-rag \
--no-wait
```

3. Connect to cluster

```
az aks get-credentials -n $(terraform output -raw aks_name) -g $(terraform output -raw rg_name)
```
 
4. Deploy a Workspace

```
kubectl apply -f - <<EOF
apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-phi-4-mini-instruct
resource:
  instanceType: Standard_NC24ads_A100_v4
  labelSelector:
    matchLabels:
      apps: phi-4-mini-instruct
inference:
  preset:
    name: phi-4-mini-instruct
EOF
```

5. Deploy a RAGEngine

```
PREFERRED_NODE_NAME=$(k get nodes -lapps=phi-4-rag -ojsonpath='{.items[0].metadata.name}')

kubectl apply -f - <<EOF
apiVersion: kaito.sh/v1alpha1
kind: RAGEngine
metadata:
  name: ragengine-phi-4-mini
spec:
  compute:
    preferredNodes:
      - $PREFERRED_NODE_NAME
    labelSelector:
      matchLabels:
        apps: phi-4-rag
  embedding:
    local:
      modelID: BAAI/bge-small-en-v1.5
  inferenceService:  
    url: http://workspace-phi-4-mini/v1/completions
EOF
```

When doing a get on the RAGEngine custom resource, I see the RAGEngine that was just deployed, but it's reporting the instance type as `Standard_NC24ads_A100_v4`.

The RAGEngine deployment never succeeds.

**Expected behavior**
If you run `kubectl get rageengine` you should see the resource with instance set to `standard_d8as_v4` which is the same as the node pool and ragengine pod should deploy to existing node

**Logs**

Describe RAGEngine custom resource

```
k describe ragengine
Name:         ragengine-phi-4-mini
Namespace:    default
Labels:       <none>
Annotations:  ragengine.kaito.io/hash: 823660e5c0c365034ac1ab4f511f728aadcfbaeca4aeb8c87e9e6ea6bde1d108
              ragengine.kaito.io/revision: 1
API Version:  kaito.sh/v1alpha1
Kind:         RAGEngine
Metadata:
  Creation Timestamp:  2025-07-12T00:49:20Z
  Finalizers:
    ragengine.finalizer.kaito.sh
  Generation:        1
  Resource Version:  6353
  UID:               d00a65dd-3bd5-4a13-befe-762510b50055
Spec:
  Compute:
    Count:          1
    Instance Type:  Standard_NC24ads_A100_v4
    Label Selector:
      Match Labels:
        Apps:  phi-4-rag
    Preferred Nodes:
      aks-ragpool-36049297-vmss000000
  Embedding:
    Local:
      Model ID:  BAAI/bge-small-en-v1.5
  Inference Service:
    URL:  http://workspace-phi-4-mini/v1/completions
Status:
  Conditions:
    Last Transition Time:  2025-07-12T00:50:21Z
    Message:               node plugin installation timed out. node aks-ragpool-36049297-vmss000000 is not ready
    Observed Generation:   1
    Reason:                ragengineResourceStatusFailed
    Status:                False
    Type:                  ResourceReady
    Last Transition Time:  2025-07-12T00:50:21Z
    Message:               node plugin installation timed out. node aks-ragpool-36049297-vmss000000 is not ready
    Observed Generation:   1
    Reason:                ragengineFailed
    Status:                False
    Type:                  RAGEngineSucceeded
Events:                    <none>
```

**Environment**

- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Install tools:
- Others:

**Additional context**

### PR DESCRIPTION
**Pull request by zhuangqh**
**Issue Fixed**:

Fixes #1256 

fix a bug: don't select node with instanceType label in preferred node mode

### CODE REVIEW

File: pkg/ragengine/controllers/ragengine_controller.go [hunk 1]
```diff
@@ -431,6 +430,14 @@ func (c *RAGEngineReconciler) applyRAGEngineResource(ctx context.Context, ragEng
 	return nil
 }
 
+func isKnownGPUInstanceType(resource *kaitov1alpha1.ResourceSpec) bool {
```
Comment (chewong) [inline pkg/ragengine/controllers/ragengine_controller.go]: Why not share the same util function with Workspace by sharing the same function signature:

```suggestion
func isKnownGPUInstanceType(instanceType string, hasPreferredNodes bool) bool {
```

Comment (zhuangqh) [reply pkg/ragengine/controllers/ragengine_controller.go]: It's a simple condition check. I place it in the caller side now.

**Review by Fei-Guo — COMMENTED** [review]
Change The system -> The controller  in the api comments.

**Review by Fei-Guo — APPROVED** [review]
